### ISSUE TITLE
/health not working but other endpoints do

### ISSUE THREAD

**Issue by ascheman** [jugda/dukecon_server#80]
Currently we have the situation that the `/health` endpoint in production (both Javaland and DOAG) does not respond but other endpoints (`/info`, `/rest/conferences`, ...) return results.

How could we further investigate this problem in productive environments (extend debugging, check via InspectIt, ...)?

**Comment by ascheman** [comment]
Meanwhile `/rest/conferences` was not available any longer - restarted both production servers.

**Comment by ahus1** [comment]
@ascheman My two cents about further investigation: get a thread dump, if possible even a heap dump. There are multiple ways to create a thread dump, see https://stackoverflow.com/questions/4876274/kill-3-to-get-java-thread-dump

**Comment by ascheman** [comment]
@ahus1 I had already tried that some time ago but for some reason did not succeed (probably since I always tried to perform the thread dump when the JVM was already completely dead?).

However, (@sippsack), today I was successful running a thread dump and it showed 102 threads blocked here:
```
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.dukecon.server.repositories.WebResourceDataProvider.checkCache(WebResourceDataProvider.groovy:49)
        - waiting to lock <0x00000000a2e424f0> (a org.dukecon.server.repositories.WebResourceDataProvider)
```

**Comment by sippsack** [comment]
let's have a look on it next weekend

**Comment by ascheman** [comment]
Looks like all threads are finally blocked by one request to DOAG which never returns:

```

"http-nio-8080-exec-8" #41 daemon prio=5 os_prio=0 tid=0x0000557d13256000 nid=0x37 runnable [0x00007f7342915000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        - locked <0x00000000b7691ac0> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000000b7693138> (a sun.security.ssl.AppInputStream)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000000b76994e0> (a java.io.BufferedInputStream)
        at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689)
        - locked <0x00000000b76994a0> (a sun.net.www.http.ChunkedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3393)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000000b768f2d0> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.Reader.read(Reader.java:140)
        at groovy.json.internal.IO.copyLarge(IO.java:82)
        at groovy.json.internal.IO.copyLarge(IO.java:74)
        at groovy.json.internal.IO.copy(IO.java:66)
        at groovy.json.internal.IO.read(IO.java:51)
        at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:127)
        at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:137)
        at groovy.json.JsonSlurper.parse(JsonSlurper.java:260)
        at groovy.json.JsonSlurper$parse.call(Unknown Source)
        at org.dukecon.server.repositories.doag.DoagJsonMapper.parseResource(DoagJsonMapper.groovy:44)
        at sun.reflect.GeneratedMethodAccessor362.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at org.dukecon.server.repositories.doag.DoagJsonMapper$_parseResources_closure2.doCall(DoagJsonMapper.groovy:34)
        at sun.reflect.GeneratedMethodAccessor361.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
...
```

**Comment by sippsack** [comment]
it is a synchronized block calling a synchronized method left over from our earlier implementation with hystrix.

**Comment by srose** [comment]
@ascheman @sippsack is this still an issue?

**Comment by ascheman** [comment]
Probably: We ran into this with our old Nagios based monitoring. We should check again when Prometheus is in regular use (@AntjeL)
